'use client'

/**
 * The stage-2 DIRECTOR PASS — character dossiers, then acting direction per shot.
 *
 * Lived inside BreakdownView as two closures, which meant only the MANUAL path could
 * run it. Measured on BLOOM (generated by the autopilot, read 2026-08-06): all 10
 * characters had personality/backstory/wardrobe/acting empty — 0 chars each — and all
 * 41 shots had `performance` empty, because AutopilotController writes its own stage 2
 * and never mounted the view these functions lived in.
 *
 * That is not cosmetic. `performance` is READ twice downstream: claude_agents.py folds
 * it into the storyboard beat writer's shot lines, and FinalGenView sends it to the
 * render as directorNotes, where assemble_video_prompt honours it as a hard directive.
 * An unattended run therefore rendered a whole film with no acting direction anywhere,
 * and every layer reported success.
 *
 * THIS FILE IS THE ONLY IMPLEMENTATION. Both entry points — BreakdownView.handleGenerate
 * (manual) and AutopilotController's stage 2 (unattended) — call `runDirectorPass`.
 * Extracting it and leaving BreakdownView's copies in place, which is the state this
 * file was found in on 2026-08-07, is worse than not extracting it: it was imported by
 * ZERO files, so it was dead code, and the live copies kept drifting.
 *
 * ORDER IS LOAD-BEARING: autoEnhanceShots reads the cast's acting master profiles out
 * of the store and sends them with every batch, so the batches (concurrent and blind to
 * each other) re-express the SAME person instead of inventing one each. Run before
 * autoEnrichCharacters — or concurrently with it — and that array is empty.
 */

import { usePipelineStore } from '@/store/pipeline.store'
import { useAgentsStore } from '@/store/agents.store'
import { pipelineApi } from '@/lib/api/pipeline.api'
import { syncSegmentsFromShots } from '@/lib/segments'
import type { BreakdownData } from '@/lib/types/pipeline.types'

/** The stage-2 breakdown as it is in the store RIGHT NOW — QC, edits and the previous
 *  pass of this file all land on the active version between these two calls. */
const currentBreakdown = (fallback: BreakdownData): BreakdownData => {
  const st = usePipelineStore.getState().stages[2]
  return (st.versions.find((v) => v.id === st.activeVersionId)?.data as BreakdownData | undefined) ?? fallback
}

const errText = (e: unknown) => (e instanceof Error ? e.message : String(e ?? 'failed'))

export interface EnrichOutcome {
  /** Characters that NEEDED a dossier. 0 = nothing to do, which is not a failure. */
  attempted: number
  enriched: number
  failed: number
  /** The NAMES behind `failed`. A count cannot be acted on: the repair for a partial
   *  failure is re-running the dossier for the specific characters that lost theirs. */
  failedNames: string[]
  /** First backend error, for the human-readable report. */
  firstError: string | null
}

export interface EnhanceOutcome {
  ran: boolean
  batchesTotal: number
  batchesFailed: number
  shotsDirected: number
  /** Shots whose stale acting direction was cleared because nobody is in frame. */
  performancesCleared: number
  /** Shots naming an assetsUsed id that is in NO asset table entry. Their cast was left
   *  UNDECLARED instead of declared empty — an id that resolves to nothing is not the
   *  same fact as "no character in this shot", and only the second one may strip the
   *  acting direction. Counted so the difference is reported, not swallowed. */
  castUndeclared: number
  /** A few of those shot ids, for the human-readable report. */
  castUndeclaredSample: string[]
  firstError: string | null
}

export interface DirectorPassOutcome {
  enrich: EnrichOutcome
  enhance: EnhanceOutcome
  /** Characters in the breakdown, and how many carry an acting master profile after
   *  enrichment — the input the shot pass actually depends on. */
  castExpected: number
  castAvailable: number
  /** WHO is performing without a master profile, read off the store after enrichment.
   *  Deliberately derived from the DATA and not from `enrich.failedNames`, because the
   *  two are not the same set: a 200 carrying an empty `acting` field never increments
   *  `failed`, so a cast can be missing profiles with zero recorded failures. This is
   *  the list an operator can act on — it names exactly the re-runs to make. */
  castMissing: string[]
  /** Set when a human MUST be told: the pass did not do what it says on the tin. */
  error: string | null
  /** Set when the pass ran but degraded. */
  warning: string | null
}

// Director pass: fill personality/backstory/wardrobe for every character that
// has none yet — concurrent (4 at a time), patched once so it never re-renders
// the table per character. Runs automatically after a breakdown; safe to re-run
// (only touches characters with an empty dossier, so it won't clobber edits).
/** What the character SAYS and DOES in the breakdown — which came from the script.
 *  Exported because the per-character button in the sidebar used to enrich from the
 *  one-line visual description alone and produced a dossier for a character who does not
 *  exist in this film: the same prompt, grounded or not, is the difference between "he
 *  blinks three times before lying" about THIS man and about a generic nervous man. Two
 *  copies of this would drift; there is one. */
export const scriptContextFor = (bd: BreakdownData, id: string): string => {
  const lines = bd.shots.flatMap((s) => (s.dialogue ?? []).filter((d) => d.characterId === id).map((d) => `"${d.text}"`))
  const acts = bd.shots.filter((s) => (s.assetsUsed ?? []).includes(id)).map((s) => s.action).filter(Boolean)
  return [
    lines.length ? `Their lines in the script: ${lines.slice(0, 10).join(' ')}` : '',
    acts.length ? `What they do (shot actions): ${acts.slice(0, 15).join('; ')}` : '',
  ].filter(Boolean).join('\n')
}

export const autoEnrichCharacters = async (bd: BreakdownData): Promise<EnrichOutcome> => {
  const { patchStageData } = usePipelineStore.getState()
  const { updateAgent } = useAgentsStore.getState()
  // A character is "done" only when it has BOTH the prose dossier and the acting master
  // profile. Filtering on personality alone would permanently skip every character that
  // was enriched before the acting field existed — they would keep a dossier and never
  // get a performance.
  const chars = bd.assets.filter((a) => a.type === 'character'
    && !(a.personality?.trim() && a.acting?.trim()))
  if (!chars.length) return { attempted: 0, enriched: 0, failed: 0, failedNames: [], firstError: null }
  updateAgent('breakdown', { status: 'active', detail: `Director: writing ${chars.length} character dossier(s)…` })
  const results: Record<string, { personality?: string; backstory?: string; wardrobe?: string; acting?: string }> = {}
  // COUNT the failures instead of swallowing them. The bare `catch { /* skip */ }` here
  // is what let a 502 from /api/character/enrich (server.py:2507) wipe out all 10 BLOOM
  // dossiers while the Breakdown Agent panel read COMPLETED — measured 3/3 runs.
  let failed = 0
  const failedNames: string[] = []
  let firstError: string | null = null
  let idx = 0
  const worker = async () => {
    for (;;) {
      const i = idx++
      if (i >= chars.length) return
      const c = chars[i]
      try {
        results[c.id] = await pipelineApi.enrichCharacter(c.name, c.visualDescription, scriptContextFor(bd, c.id))
      } catch (e) {
        failed++
        // NAME the casualty. Counting them was enough to prove the pass degraded and not
        // enough to repair it: measured 2026-08-07 with 3 of 10 characters answering 502,
        // 3/3 runs on both paths, the operator was shown "7/10 … 3 failed" and the three
        // names appeared in no toast, no agent card and no console line.
        failedNames.push(c.name)
        if (!firstError) firstError = errText(e)
      }
    }
  }
  await Promise.all(Array.from({ length: Math.min(4, chars.length) }, worker))
  const enriched = Object.keys(results).length
  // Partial results are still worth writing — 7 real dossiers beat 0. Only skip the
  // patch when there is literally nothing to write.
  if (enriched) {
    // Patch onto whatever the active breakdown is now (may have QC/edits since).
    const cur = currentBreakdown(bd)
    patchStageData(2, {
      ...cur,
      assets: cur.assets.map((a) => results[a.id]
        ? {
            ...a,
            personality: a.personality?.trim() ? a.personality : (results[a.id].personality ?? ''),
            backstory: a.backstory?.trim() ? a.backstory : (results[a.id].backstory ?? ''),
            wardrobe: a.wardrobe?.trim() ? a.wardrobe : (results[a.id].wardrobe ?? ''),
            // Same never-clobber rule as the three above: a profile the user wrote by
            // hand survives a re-run of the director pass.
            acting: a.acting?.trim() ? a.acting : (results[a.id].acting ?? ''),
          }
        : a),
    })
  }
  // No terminal agent state here — runDirectorPass owns it, because only it knows
  // whether the shot pass then ran. Setting 'completed' here is precisely how a failed
  // dossier pass came to be reported as a success.
  return { attempted: chars.length, enriched, failed, failedNames, firstError }
}

// Auto-enhance every shot's action + visual after a breakdown — BATCHED (≈15
// shots per Seed call, 3 batches concurrent) so 61 shots is ~4 calls, not 122.
// Gated by the "Auto-enhance shots" toggle on the MANUAL path (off it for very long
// films). The unattended path has no toggle: runDirectorPass is called with
// enhanceShots=true from AutopilotController, so an autopilot run always gets it.
export const autoEnhanceShots = async (bd: BreakdownData): Promise<EnhanceOutcome> => {
  const { patchStageData } = usePipelineStore.getState()
  const { updateAgent } = useAgentsStore.getState()
  const shots = bd.shots
  const nil: EnhanceOutcome = { ran: false, batchesTotal: 0, batchesFailed: 0, shotsDirected: 0, performancesCleared: 0, castUndeclared: 0, castUndeclaredSample: [], firstError: null }
  if (!shots.length) return nil
  updateAgent('breakdown', { status: 'active', detail: `Director: polishing ${shots.length} shot(s)…` })
  const BATCH = 15
  const batches: BreakdownData['shots'][] = []
  for (let i = 0; i < shots.length; i += BATCH) batches.push(shots.slice(i, i + BATCH))
  // Read the cast from the store rather than from `bd`: autoEnrichCharacters runs just
  // before this and writes the acting profiles onto a NEW version, so `bd` — the
  // breakdown as it was when this pass started — still has them empty.
  const castSrc = currentBreakdown(bd)
  const cast = castSrc.assets
    .filter((a) => a.type === 'character' && a.acting?.trim())
    .map((a) => ({ name: a.name, acting: a.acting }))
  // WHO IS IN EACH SHOT. Only this side knows an asset's TYPE — the backend receives ids
  // and can't tell a character from a prop — so the caller resolves assetsUsed here and
  // sends names; a shot that resolves to NOBODY comes back with no acting direction
  // (ACTING SKILL §8.1). Measured on BLOOM: 6 of 41 shots have no character asset and 17
  // of those 18 performances (3 runs) were the director answering "No human present.",
  // camera notes included. Both versions' assets are read because enrich rewrites the array.
  const charNameById = new Map<string, string>(
    [...bd.assets, ...castSrc.assets].filter((a) => a.type === 'character').map((a) => [a.id, a.name]))
  // The valve: a breakdown with NO character assets at all (untagged, or a film with no
  // cast) must not have every shot silently stripped — say nothing and the backend
  // behaves exactly as it did before the key existed.
  const knowsCast = charNameById.size > 0
  // …and the SECOND valve, for a fact the first one cannot express. `characters: []` is
  // an assertion — "nobody is in this frame" — and the backend deletes the acting
  // direction on the strength of it. But the line below that builds it, map→get→filter,
  // silently drops an assetsUsed id that is not in the asset table AT ALL, so a shot whose
  // only tagged asset is a dangling id resolved to [] and got its performance stripped on
  // the strength of an assertion nobody made. Those are different facts: an id that
  // resolves to a PROP means no character (true, strip it); an id that resolves to nothing
  // means we do not know (say nothing, and the shot is directed exactly as it was before
  // any of this existed). BLOOM has 0 dangling ids today — this is a latent silent
  // false-strip, and it is reported below rather than swallowed.
  const knownAssetIds = new Set<string>([...bd.assets, ...castSrc.assets].map((a) => a.id))
  const danglingByShot = new Map<string, string[]>()
  for (const s of shots) {
    const unknown = (s.assetsUsed ?? []).filter((id) => id && !knownAssetIds.has(id))
    if (unknown.length) danglingByShot.set(s.id, unknown)
  }
  const merged: Record<string, { action?: string; visual?: string; performance?: string }> = {}
  let batchesFailed = 0
  let firstError: string | null = null
  let bi = 0
  const worker = async () => {
    for (;;) {
      const i = bi++
      if (i >= batches.length) return
      try {
        const res = await pipelineApi.enhanceShots(
          // Pass dialogue so the director grounds the acting direction in what's said.
          batches[i].map((s) => ({
            id: s.id, action: s.action, visual_description: s.visualDescription,
            // WHO SPEAKS. A DialogueLine is stored as {characterId:'ASSET_004', text,
            // emotion} and the backend has no asset table, so `s.dialogue` raw reached
            // the director with no speaker at all: measured on BLOOM 2026-08-07, 27 of 27
            // lines arrived as a bare colon (': "Come out Sunday…"'), and on the 13
            // multi-character dialogue shots × 6 runs the acting note put the line in the
            // wrong actor's mouth 9 times out of 78 — 0/78 once the name is sent (Fisher
            // p=0.0031). SHOT_024 is the readable case: the line is Beni's and all 6
            // unfixed runs had Tomás say it. Resolving the NAME belongs HERE for exactly
            // the reason `characters` does — this is the only side holding the id→asset
            // map; the same idiom StoryboardView/FinalGenView already use. An id that
            // does not resolve leaves `character` empty and the backend falls back to
            // characterId itself, so the end result matches their `?? d.characterId`
            // without spelling the fallback twice. `...d` keeps characterId on the wire.
            dialogue: (s.dialogue ?? []).map((d) => ({ ...d, character: charNameById.get(d.characterId) ?? '' })),
            // `characters` is an ASSERTION about the cast, so it is only made when it can
            // be: a shot carrying an unresolvable asset id says nothing (see danglingByShot).
            ...(knowsCast && !danglingByShot.has(s.id)
              ? { characters: (s.assetsUsed ?? []).map((id) => charNameById.get(id)).filter((n): n is string => !!n) }
              : {}),
          })),
          // …and the cast's acting master profiles, so each batch re-expresses the SAME
          // person. The batches run concurrently and blind to each other, so without this
          // the only thing tying batch 1's Tomás to batch 3's is the name.
          cast)
        Object.assign(merged, res)
      } catch (e) {
        batchesFailed++
        if (!firstError) firstError = errText(e)
      }
    }
  }
  await Promise.all(Array.from({ length: Math.min(3, batches.length) }, worker))
  const undeclared = [...danglingByShot.keys()]
  if (undeclared.length) {
    // Loud on the console AND counted into the outcome below, which is what puts it in
    // front of a human. A dangling assetsUsed id is a real breakdown defect (stage 3 and
    // stage 5 resolve the same ids for reference images) and used to be absorbed by a
    // `.filter(Boolean)` that turned it into the innocuous-looking sentence "no character
    // in this shot".
    console.warn('[DirectorPass] assetsUsed names ids that are in no asset:',
      [...danglingByShot.entries()].map(([sid, ids]) => `${sid}→${ids.join(',')}`).join(' | '))
  }
  const undeclaredFields = { castUndeclared: undeclared.length, castUndeclaredSample: undeclared.slice(0, 4) }
  if (!Object.keys(merged).length) {
    return { ran: true, batchesTotal: batches.length, batchesFailed, shotsDirected: 0, performancesCleared: 0, ...undeclaredFields, firstError }
  }
  const cur = currentBreakdown(bd)
  let performancesCleared = 0
  const nextShots = cur.shots.map((s) => {
    const m = merged[s.id]
    if (!m) return s                       // the director said nothing about this shot
    // THE THREE CASES. `performance` used to be merged with
    //     s.performance || m.performance || s.performance
    // which can only ever ADD a value, never clear one — so when the backend started
    // deliberately returning "" for a shot with nobody in frame, the log said "no acting
    // direction written" and the data kept the old paragraph. Measured against BLOOM's
    // real state: 6/6 character-less shots KEPT a stale value (SHOT_009 kept "Locked off
    // static frame … no camera motion.", i.e. a CAMERA note in the acting field).
    //   · key present, non-empty → the director WROTE direction. Never clobber what is
    //     already there — that rule predates this fix and is why the OR-chain existed.
    //   · key present, ""        → the director DELIBERATELY CLEARED it (backend only
    //     emits "" for a shot whose cast we told it was empty). Clear the stale value.
    //   · key ABSENT             → the director SAID NOTHING (model dropped the field, or
    //     the batch failed). Never touch the field on a non-answer.
    // A HAND-WRITTEN performance outranks all of it: `performanceSource === 'manual'` is
    // stamped by BreakdownView.handleEditShot and survives even the deliberate clear.
    let performance = s.performance
    if (Object.prototype.hasOwnProperty.call(m, 'performance')) {
      const written = (m.performance ?? '').trim()
      if (written) {
        performance = s.performance || m.performance
      } else if (s.performanceSource !== 'manual') {
        if ((s.performance ?? '').trim()) performancesCleared++
        performance = ''
      }
    }
    return {
      ...s,
      action: m.action || s.action,
      visualDescription: m.visual || s.visualDescription,
      performance,
    }
  })
  patchStageData(2, syncSegmentsFromShots({ ...cur, shots: nextShots }))
  return {
    ran: true, batchesTotal: batches.length, batchesFailed,
    shotsDirected: Object.keys(merged).length, performancesCleared, ...undeclaredFields, firstError,
  }
}

/**
 * THE entry point. Both paths call this so there is one order, one policy and one
 * terminal agent state.
 *
 * POLICY on a failed/partial dossier pass — decided 2026-08-07, and it is not cosmetic.
 * An independent experiment put ~79% of acting quality on the cast's master profiles,
 * and the shot merge NEVER clobbers an existing performance. So a shot pass run with an
 * empty cast does not merely produce weaker direction: it writes that weaker direction
 * permanently, and a later successful enrichment can no longer repair it. An EMPTY
 * `performance` is repairable; a bad one is not.
 *   · a cast was expected and none of it materialised → STOP. Do not run the shot pass.
 *     Report it. Leaving the field empty keeps the project fixable.
 *   · a cast was expected and part of it materialised → RUN, and NAME who is missing.
 *     The profiles that did land are real and carry the batches that use them.
 *   · no characters in the breakdown at all → RUN unchanged. That is a legitimate
 *     breakdown (untagged, or a film with no cast), not a failure, and it is the
 *     `knowsCast === false` valve the backend already honours.
 *
 * WHY "RUN" AND NOT "REFUSE" ON A PARTIAL CAST — argued from the same ~79% figure that
 * justifies stopping on a total one, which is why the two branches differ. With 7 of 10
 * profiles in hand, refusing costs the 7 characters who WOULD have been directed
 * correctly in order to protect the 3 who would not; running costs the 3 and keeps the
 * 7. The asymmetry that makes stopping right at 0 does not exist at 7: there is no cast
 * to re-express, so a total-failure run writes nothing BUT generic direction, and the
 * merge's never-clobber rule makes it permanent.
 *
 * That trade is only defensible if the 3 are LEGIBLE, and until 2026-08-07 they were
 * not. Measured, 10 characters with 3 injected 502s, 3/3 runs on both paths: the shot
 * pass ran with a 7-name cast, the per-shot cast still named all ten, and the only thing
 * a human saw was "7/10 character dossier(s) written — 3 failed". WHICH three was in no
 * toast, no agent card, no console line — so the operator could not re-run just them,
 * which is the entire repair. `castMissing` below names them, in the toast, on the card
 * and (in full, uncapped) on the console.
 */
export const runDirectorPass = async (
  bd: BreakdownData,
  opts: { enhanceShots: boolean },
): Promise<DirectorPassOutcome> => {
  const { updateAgent } = useAgentsStore.getState()
  const enrich = await autoEnrichCharacters(bd)

  // Judge the cast on the DATA that reached the store, not on the call counters: an
  // enrich that returns 200 with an empty `acting` is just as empty an input as a 502.
  const after = currentBreakdown(bd)
  const castChars = after.assets.filter((a) => a.type === 'character')
  const castExpected = castChars.length
  const castAvailable = castChars.filter((a) => a.acting?.trim()).length
  // WHO, not how many. Read off the store for the same reason castAvailable is: a 200
  // carrying an empty `acting` leaves a character just as unprofiled as a 502 does, and
  // does not increment enrich.failed — so a list built from the failures alone would have
  // been silent in exactly the case nobody is watching for.
  const castMissing = castChars.filter((a) => !a.acting?.trim()).map((a) => a.name).filter(Boolean)

  const enrichNote = enrich.failed
    ? `${enrich.enriched}/${enrich.attempted} character dossier(s) written — ${enrich.failed} failed`
      + (enrich.firstError ? ` (${enrich.firstError.slice(0, 120)})` : '')
    : ''

  let enhance: EnhanceOutcome = { ran: false, batchesTotal: 0, batchesFailed: 0, shotsDirected: 0, performancesCleared: 0, castUndeclared: 0, castUndeclaredSample: [], firstError: null }

  if (castExpected > 0 && castAvailable === 0) {
    const detail = `Director pass FAILED — no character dossiers. ${enrichNote || `0/${castExpected} characters have an acting profile.`}`
      + ' Shot direction was SKIPPED on purpose: writing it without the cast would bake in'
      + ' direction that a later run cannot replace.'
    updateAgent('breakdown', { status: 'error', detail })
    return { enrich, enhance, castExpected, castAvailable, castMissing, error: detail, warning: null }
  }

  if (opts.enhanceShots) enhance = await autoEnhanceShots(bd)

  // ONE terminal state, set from the whole outcome.
  const problems: string[] = []
  // FIRST, because it is the consequence the operator has to act on — the enrich counts
  // below are only the cause. A toast is read from the top and truncates at the bottom.
  if (castMissing.length && castMissing.length < castExpected) {
    // The console keeps the FULL list; the toast is a ~380px card, so it shows the first
    // 12 and says how many more. Same shape as the danglingByShot warning above, and for
    // the same reason: the readable channel and the complete channel are not the same one.
    console.warn('[DirectorPass] characters with NO acting master profile — they will be '
      + 'directed generically, re-run their dossier to repair:', castMissing.join(', '))
    const shown = castMissing.slice(0, 12)
    problems.push(`${castMissing.length}/${castExpected} character(s) have NO acting profile and `
      + `will be directed generically: ${shown.join(', ')}`
      + (castMissing.length > shown.length ? ` (+${castMissing.length - shown.length} more)` : ''))
  }
  if (enrich.failed) problems.push(enrichNote)
  if (enhance.batchesFailed) {
    problems.push(`${enhance.batchesFailed}/${enhance.batchesTotal} shot batch(es) failed`
      + (enhance.firstError ? ` (${enhance.firstError.slice(0, 120)})` : ''))
  }
  if (enhance.ran && !enhance.shotsDirected && enhance.batchesTotal && !enhance.batchesFailed) {
    problems.push('the shot pass returned no shots')
  }
  // Not a failure of the pass — a defect in the DATA the pass was given, surfaced here
  // because the alternative (what happened before) is a silent strip.
  if (enhance.castUndeclared) {
    problems.push(`${enhance.castUndeclared} shot(s) name an asset id that does not exist `
      + `(${enhance.castUndeclaredSample.join(', ')}${enhance.castUndeclared > enhance.castUndeclaredSample.length ? ', …' : ''})`
      + ' — their cast was left undeclared, so the acting direction was kept rather than stripped')
  }

  if (problems.length) {
    const detail = `Director pass INCOMPLETE — ${problems.join(' · ')}`
    updateAgent('breakdown', { status: 'error', detail })
    return { enrich, enhance, castExpected, castAvailable, castMissing, error: null, warning: detail }
  }

  const done = [
    enrich.enriched ? `${enrich.enriched} dossier(s)` : '',
    enhance.shotsDirected ? `${enhance.shotsDirected} shot(s) directed` : '',
    enhance.performancesCleared ? `${enhance.performancesCleared} stale performance(s) cleared` : '',
  ].filter(Boolean).join(' · ')
  updateAgent('breakdown', { status: 'completed', detail: done ? `Director pass: ${done}` : 'Director pass: nothing to do' })
  return { enrich, enhance, castExpected, castAvailable, castMissing, error: null, warning: null }
}
