'use client'

import { useState, useEffect, useRef } from 'react'
import { MapPin, Sparkles, CheckCircle, ChevronDown, ChevronUp, AlertTriangle } from 'lucide-react'
import { cn } from '@/lib/utils'
import { Button } from '@/components/ui/Button'
import { QCActionCard } from '@/components/agent/QCActionCard'
import { apiClient } from '@/lib/api/client'
import { usePipelineStore } from '@/store/pipeline.store'
import type { QCResponse } from '@/lib/api/pipeline.api'

interface AngleSet {
  wide?: string
  reverse?: string
  high?: string
  eye_level?: string
}

/** Per-view mirror verdict from byteplus_generative.score_reverse_against_base.
 *  degraded=true means the reverse is STILL the base (or the base flipped) after every
 *  retry the backend was allowed. It is shipped anyway — a mirrored reverse still beats
 *  no reverse for coverage — but it must be VISIBLE: the angle sheet is the dominant
 *  environment reference for every board of this location (server._env_angle_sheet), so a
 *  flipped base propagates its flipped lettering into every render downstream. */
interface AngleCheck {
  degraded?: boolean
  mirrored?: boolean
  hamming?: number | null
  attempts?: number
  /** top_view only — verdict from byteplus_generative.score_top_view. A map that is not
   *  an overhead of THIS place is the same class of bug as a mirrored reverse, and the
   *  worst version of it invents an interior: 5 of BLOOM's 20 maps returned a room that
   *  appears in neither the base nor the description. The sheet feeds every board of the
   *  location, so an invented room teaches the model a geography the film does not have. */
  pitch_deg?: number | null
  same_place?: number | null
  invented_interior?: boolean
  invented_what?: string
  reason?: string
  /** reverse only — WHICH arm drew this sheet. 'video' = a short Seedance walk-through of
   *  the empty location, the frame at the far end of the move (Hell Grind rule 1); 'image'
   *  = the Seedream sequential set, which is the fallback and the arm that answered
   *  "rotate 180°" with a MIRROR in 15 of 31 measured draws. Both arms are accepted by the
   *  same validator, so `degraded` alone cannot tell them apart — and the operator deciding
   *  whether to trust a sheet needs to know which one it came from. */
  source?: string
  video_task_id?: string
  texture_cleanup?: boolean
  /** Only set when the video arm was asked and LOST — without it a sheet that quietly fell
   *  back to the image path is indistinguishable from one generated with the arm off. */
  video_error?: string
}
type AngleChecks = Record<string, AngleCheck>


interface Props {
  assetName: string
  description: string
  approvedUrl: string
  /** Auto-generate the sheet once (fired the moment the environment is approved). */
  autoStart?: boolean
}

const ANGLE_LABELS: Record<string, string> = {
  wide:      'Wide / Establishing',
  reverse:   'Reverse Angle',
  high:      'High / Bird\'s Eye',
  eye_level: 'Eye Level',
}

// FAST PATH ONLY — never the source of truth. The sheet lives on disk in the project
// (the POST has saved it since P5); this is a per-browser copy so the panel paints
// something before GET /api/assets/environment-angles answers. It used to be the ONLY
// seed, which meant a sheet generated by another browser, another machine, a script or
// the autopilot was invisible: the panel offered "Generate" for work already paid for
// and autoStart below re-billed it.
type AngleCache = { angles: AngleSet; topView: string | null; checks?: AngleChecks }
function readAngleCache(k: string): AngleCache | null {
  if (typeof window === 'undefined') return null
  try { const v = localStorage.getItem(k); return v ? (JSON.parse(v) as AngleCache) : null } catch { return null }
}
function writeAngleCache(k: string, angles: AngleSet, topView: string | null, checks: AngleChecks) {
  if (typeof window === 'undefined') return
  try { localStorage.setItem(k, JSON.stringify({ angles, topView, checks })) } catch { /* quota — non-fatal */ }
}

export function EnvironmentAnglesPanel({ assetName, description, approvedUrl, autoStart }: Props) {
  const style           = usePipelineStore((s) => s.style)
  const projectName     = usePipelineStore((s) => s.projectName)
  const localFolderRoot = usePipelineStore((s) => s.localFolderRoot)

  const cacheKey = `envAngles:${projectName}:${assetName}`
  const [open, setOpen] = useState(Boolean(autoStart))
  const [angles, setAngles] = useState<AngleSet>(() => readAngleCache(cacheKey)?.angles ?? {})
  const [topView, setTopView] = useState<string | null>(() => readAngleCache(cacheKey)?.topView ?? null)
  const [checks, setChecks] = useState<AngleChecks>(() => readAngleCache(cacheKey)?.checks ?? {})
  const [qcResult, setQcResult] = useState<QCResponse | null>(null)
  const [isGenerating, setIsGenerating] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const handleGenerate = async () => {
    setIsGenerating(true)
    setError(null)
    setQcResult(null)
    try {
      const { data } = await apiClient.post<{
        angles: AngleSet
        top_view: string
        qc: QCResponse | null
        angle_checks?: AngleChecks
      }>('/api/assets/environment-angles', {
        description,
        style_suffix: style.promptSuffix,   // 2b: sent separately → each angle routes through the assembler
        base_image_url: approvedUrl,
        negative_prompt: style.negativePrompt || undefined,
        project_name: projectName,
        project_path: localFolderRoot ?? '',
        asset_name: assetName,
        // 900s, not 600: the reverse now comes from a 10s Seedance walk-through, measured
        // at 140-205s wall-clock per location on top of the Seedream set, its retries and
        // the QC pass. At 600s a location that needed the top-view retry ladder as well
        // could time out in the browser while the backend kept going and kept billing.
      }, { timeout: 900_000 })
      setAngles(data.angles ?? {})
      setTopView(data.top_view || null)
      setChecks(data.angle_checks ?? {})
      writeAngleCache(cacheKey, data.angles ?? {}, data.top_view || null, data.angle_checks ?? {})
      if (data.qc) setQcResult(data.qc)
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Generation failed')
    } finally {
      setIsGenerating(false)
    }
  }

  const hasAngles = Object.keys(angles).length > 0

  // THE source of truth: what the project has on disk. Runs on mount and REPLACES the
  // localStorage seed — including with "nothing", so a cache left over from a deleted or
  // reverted sheet stops claiming angles that no longer exist. Failure (backend down, an
  // older build without the GET) keeps the cached view rather than blanking the panel.
  //
  // No race with handleGenerate: this resolves in milliseconds and the POST takes minutes,
  // and even a pathologically late answer would carry the just-saved copy — the POST
  // writes the images to disk before it returns.
  const [projectRead, setProjectRead] = useState(false)
  useEffect(() => {
    let cancelled = false
    if (!projectName) {
      // No project → disk has nothing to read, so the gate opens immediately. Deferred
      // by a tick for the same reason the autoStart fire below is: a setState run
      // SYNCHRONOUSLY in an effect body cascades an extra render pass, and
      // react-hooks/set-state-in-effect rejects it (it was a lint ERROR, not a warning).
      const t0 = setTimeout(() => setProjectRead(true), 0)
      return () => clearTimeout(t0)
    }
    void (async () => {
      try {
        const { data } = await apiClient.get<{
          angles: AngleSet; top_view: string; angle_checks?: AngleChecks
        }>(
          '/api/assets/environment-angles',
          { params: { project_name: projectName, project_path: localFolderRoot ?? '', asset_name: assetName } },
        )
        if (cancelled) return
        const fromDisk = data.angles ?? {}
        const tv = data.top_view || null
        const ck = data.angle_checks ?? {}
        setAngles(fromDisk)
        setTopView(tv)
        setChecks(ck)
        writeAngleCache(cacheKey, fromDisk, tv, ck)
      } catch {
        /* keep the cached view — see above */
      } finally {
        if (!cancelled) setProjectRead(true)
      }
    })()
    return () => { cancelled = true }
  }, [projectName, localFolderRoot, assetName, cacheKey])

  // Auto-generate ONCE when the environment is freshly approved (autoStart). The
  // trigger is deferred (setTimeout) so no setState runs synchronously inside the
  // effect; the localStorage cache + this ref prevent any re-fire.
  //
  // projectRead is the load-bearing guard: firing before the disk answer arrives is
  // exactly how an already-paid sheet got regenerated (the cache is per-browser, so a
  // fresh browser always looked empty). Wait for the project, THEN decide.
  const autoFiredRef = useRef(false)
  useEffect(() => {
    if (!autoStart || autoFiredRef.current || !projectRead || hasAngles || isGenerating || !approvedUrl) return
    autoFiredRef.current = true
    const t = setTimeout(() => { void handleGenerate() }, 0)
    return () => clearTimeout(t)
    // handleGenerate intentionally omitted — it is stable enough for a one-shot fire.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [autoStart, projectRead, hasAngles, isGenerating, approvedUrl])

  return (
    <div className="rounded-lg border border-green/20 bg-green/5 overflow-hidden">
      {/* Header */}
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center gap-2 px-3 py-2 hover:bg-text-primary/[0.04] transition-colors"
      >
        <MapPin size={12} className="text-green" />
        <span className="text-[10px] font-semibold text-green uppercase tracking-widest flex-1 text-left">
          Environment Angles + Top View
        </span>
        {hasAngles && (
          <span className="text-[9px] font-mono text-green/60 bg-green/10 border border-green/20 px-1.5 py-0.5 rounded">
            {Object.keys(angles).length} {Object.keys(angles).length === 1 ? 'angle' : 'angles'}
          </span>
        )}
        {open ? <ChevronUp size={12} className="text-text-muted" /> : <ChevronDown size={12} className="text-text-muted" />}
      </button>

      {/* Expanded content */}
      <div className={cn(
        'grid transition-[grid-template-rows] duration-300 ease-in-out',
        open ? 'grid-rows-[1fr]' : 'grid-rows-[0fr]',
      )}>
        <div className="overflow-hidden">
          <div className="border-t border-green/20 p-3 flex flex-col gap-3">
            {!hasAngles ? (
              <div className="flex flex-col items-center gap-3 py-3">
                {/* Names EXACTLY what byteplus_generative.ENVIRONMENT_VIEWS generates. It
                    promised "4 camera angles (wide, reverse, high, eye-level)" long after
                    the generator was cut to two — wide/eye-level came back as near-copies
                    of the base, and a measured 90° lateral was rejected too (4 BLOOM
                    locations × 2 trials: 5/8 three-view sets held a near-duplicate and
                    5/8 lost the overhead entirely). Two views is the honest count. */}
                <p className="text-[11px] text-text-muted text-center">
                  Generate the reverse angle + an overhead top-view map.<br />
                  Uses the approved base as reference to lock lighting and geometry.
                </p>
                {error && (
                  <p className="text-[11px] text-red">{error}</p>
                )}
                <Button
                  variant="primary"
                  size="sm"
                  icon={<Sparkles size={12} />}
                  loading={isGenerating}
                  onClick={handleGenerate}
                  className="border-green/40 text-green hover:bg-green/20"
                >
                  Generate Angles + Top View
                </Button>
              </div>
            ) : (
              <div className="flex flex-col gap-3">
                {/* Angle grid */}
                <div className="grid grid-cols-2 gap-2">
                  {Object.entries(angles)
                    .filter(([, url]) => url)
                    .map(([key, url]) => {
                      const bad = checks[key]?.degraded
                      return (
                      <div key={key} className="flex flex-col gap-1">
                        <div className={cn(
                          'relative rounded overflow-hidden border aspect-video',
                          bad ? 'border-amber-500' : 'border-border',
                        )}>
                          <img src={url} alt={key} className="w-full h-full object-cover" />
                          {/* Shipped but not trusted — see AngleCheck above. Named, not a
                              generic "QC failed": the person looking at it has to know the
                              reference itself is flipped before they build boards on it. */}
                          {bad && (
                            <span
                              className="absolute top-1 left-1 flex items-center gap-1 rounded bg-amber-500/90 px-1 py-0.5 text-[8px] font-semibold text-black"
                              title={`Rejected as a copy of the base${checks[key]?.mirrored ? ' (mirrored)' : ''}`
                                + ` after ${checks[key]?.attempts ?? 1} attempt(s)`
                                + ` — dHash distance ${checks[key]?.hamming ?? '?'} of 64.`
                                + ' Regenerate before using this sheet as a reference.'}
                            >
                              <AlertTriangle size={8} />
                              {checks[key]?.mirrored ? 'MIRRORED BASE' : 'BASE COPY'}
                            </span>
                          )}
                        </div>
                        <span className="text-[9px] text-text-muted text-center">
                          {ANGLE_LABELS[key] ?? key}
                          {/* WHICH arm drew it. Shown always, not only on failure: an
                              image-path reverse is a 48%-mirror draw that merely passed
                              the validator this time, and that is worth knowing BEFORE
                              boards are built on it. */}
                          {checks[key]?.source && (
                            <span
                              className={cn('ml-1 font-mono',
                                checks[key]?.source === 'video' ? 'text-green/70' : 'text-amber-500/80')}
                              title={checks[key]?.source === 'video'
                                ? `From a ${''}Seedance walk-through of the empty location`
                                  + `${checks[key]?.texture_cleanup ? ', textures/lighting cleaned in Seedream' : ''}`
                                  + `${checks[key]?.video_task_id ? ` (task ${checks[key]?.video_task_id})` : ''}.`
                                : 'From the Seedream image set — the walk-through was off or failed'
                                  + `${checks[key]?.video_error ? `: ${checks[key]?.video_error}` : ''}.`}
                            >
                              [{checks[key]?.source === 'video' ? 'VIDEO' : 'IMG'}]
                            </span>
                          )}
                        </span>
                      </div>
                      )
                    })
                  }
                </div>

                {/* Top-view map */}
                {topView && (
                  <div className="flex flex-col gap-1">
                    <p className="text-[9px] font-semibold text-text-muted uppercase tracking-widest">
                      Top View / Floor Plan
                    </p>
                    <div className={cn(
                      'relative rounded overflow-hidden border aspect-video w-full',
                      checks.top_view?.degraded ? 'border-amber-500' : 'border-border',
                    )}>
                      <img src={topView} alt="Top View Map" className="w-full h-full object-cover" />
                      {/* Shipped but not trusted — see AngleCheck above. INVENTED ROOM is
                          named separately from NOT OVERHEAD because they cost different
                          things: a steep-but-not-plan view is still the right place, an
                          invented room is a location the film does not have. */}
                      {checks.top_view?.degraded && (
                        <span
                          className="absolute top-1 left-1 flex items-center gap-1 rounded bg-amber-500/90 px-1 py-0.5 text-[8px] font-semibold text-black"
                          title={(checks.top_view?.invented_interior
                            ? `Shows a space that is in neither the base nor the description${
                                checks.top_view?.invented_what ? `: ${checks.top_view.invented_what}` : ''}. `
                            : `Not an overhead of this location — camera pitch ${checks.top_view?.pitch_deg ?? '?'}°, below the 40° a plan view needs. `)
                            + `Rejected after ${checks.top_view?.attempts ?? 1} attempt(s).`
                            + ' Regenerate before using this sheet as a reference.'}
                        >
                          <AlertTriangle size={8} />
                          {checks.top_view?.invented_interior ? 'INVENTED ROOM' : 'NOT OVERHEAD'}
                        </span>
                      )}
                    </div>
                  </div>
                )}

                {/* QC result */}
                {qcResult && (
                  <QCActionCard
                    qcResult={qcResult}
                    context={`${assetName} — Layout Director`}
                    onRegenerate={handleGenerate}
                  />
                )}

                {/* Regenerate */}
                <Button
                  variant="regenerate"
                  size="sm"
                  icon={<Sparkles size={12} />}
                  loading={isGenerating}
                  onClick={handleGenerate}
                  className="w-full"
                >
                  Regenerate Angles
                </Button>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}
