import { test, expect, noInheritedProject } from './isolation'
import { openAutopilot } from './hydration'

/**
 * The stage-2 DIRECTOR PASS on the unattended path.
 *
 * Measured on BLOOM (generated by autopilot, 2026-08-06): all 10 characters had
 * personality/backstory/wardrobe/acting empty (0 chars each) and all 41 shots had
 * `performance` empty. The manual path runs two passes after the breakdown lands —
 * character dossiers, then shot direction — and the autopilot ran neither: it
 * generated, QC'd and approved stage 2 without ever calling them, because both passes
 * lived in BreakdownView's component body and that view is never mounted during an
 * unattended run.
 *
 * That is not cosmetic. `performance` is read in two places downstream
 * (claude_agents.py folds it into the storyboard beat writer; FinalGenView sends it
 * to the render as directorNotes, which assemble_video_prompt honours as a hard
 * directive), so an unattended run rendered a whole film with zero acting direction
 * while every layer reported success.
 *
 * The ORDER is load-bearing and is asserted here, not assumed: the shot pass takes
 * the cast's acting master profiles as input, so it must see a cast that has already
 * been enriched. Running the two concurrently would send an empty cast and each
 * batch would invent its own version of the same person.
 *
 * RECONCILED 2026-08-07: the original version of this spec asserted a non-empty
 * `performance` on EVERY shot. That is now wrong BY DESIGN — the backend deliberately
 * returns "" for a shot with nobody in frame (ACTING SKILL §8.1: "no character in
 * frame → no paragraph"), because 17 of 18 such performances in a measured BLOOM run
 * were the director answering "No human present." with camera notes attached. SHOT_004
 * below is that case and is asserted EMPTY; the peopled shots are asserted non-empty.
 *
 * All four endpoints are route-mocked for determinism; the stage-3 image endpoints
 * are stubbed to fail so landing at stage 3 cannot start real generation.
 */

interface Persisted {
  stages: Record<string, {
    status: string
    activeVersionId: string | null
    versions: Array<{ id: string; data: { assets?: Array<Record<string, string>>; shots?: Array<Record<string, string>> } }>
  }>
}

const readStore = async (page: import('@playwright/test').Page): Promise<Persisted> =>
  await page.evaluate(() => JSON.parse(localStorage.getItem('takeone-pipeline-v1')!).state)

test('autopilot runs the stage-2 director pass — dossiers first, then shot direction', async ({ page }) => {
  await noInheritedProject(page)

  // ── Calls the director pass makes, in order ────────────────────────────────
  const order: string[] = []
  const enrichNames: string[] = []
  const enhanceCastSeen: Array<Array<{ name: string; acting?: string }>> = []
  // What the caller said about WHO is in each shot — the input the backend's
  // no-acting-direction gate keys on.
  const castPerShot: Record<string, string[] | undefined> = {}

  // The script has to CONTAIN the line SHOT_002's fixture speaks. This spec is about the
  // director pass, not about dialogue, but /api/breakdown/qc is NOT stubbed here — it
  // reaches the real backend, whose "Dialogue fidelity" gate (blocking, 2026-08-13) fails
  // any breakdown that speaks words the screenplay never wrote. Without the cue below the
  // fixture was exactly that case, the gate stopped the unattended run at stage 2, and
  // this spec failed for a reason that has nothing to do with dossiers. The gate was
  // right; the fixture was not.
  await page.route('**/api/script/generate', (r) => r.fulfill({
    status: 200, contentType: 'application/json',
    body: JSON.stringify({ content: 'FADE IN. A neon city at night. KANE walks the flooded streets. MIRA waits.\n\nKANE\nYou are not her.\n\nTHE END.' }),
  }))
  await page.route('**/api/breakdown/generate', (r) => r.fulfill({
    status: 200, contentType: 'application/json',
    body: JSON.stringify({
      assets: [
        { id: 'ASSET_001', name: 'Detective Kane', type: 'character', visual_description: 'noir detective in a trench coat' },
        { id: 'ASSET_002', name: 'Mira', type: 'character', visual_description: 'a rogue AI wearing a stolen face' },
        // An ENVIRONMENT, so SHOT_004 has a non-empty assetsUsed that still resolves to
        // NOBODY. That is the real shape of BLOOM's 6 character-less shots — not an
        // untagged shot, but a shot whose only assets are places and things.
        { id: 'ASSET_003', name: 'Flooded street', type: 'environment', visual_description: 'black water to the knee' },
      ],
      shots: [
        { id: 'SHOT_001', scene: 'INT. CITY - NIGHT', action: 'walks toward the camera', visual_description: 'detective walks', assets_used: ['ASSET_001'], duration_sec: 5 },
        { id: 'SHOT_002', scene: 'INT. CITY - NIGHT', action: 'turns to face her', visual_description: 'he stops', assets_used: ['ASSET_001', 'ASSET_002'], duration_sec: 5,
          dialogue: [{ characterId: 'ASSET_001', character: 'Detective Kane', text: 'You are not her.' }] },
        { id: 'SHOT_003', scene: 'INT. CITY - NIGHT', action: 'she smiles', visual_description: 'Mira smiles', assets_used: ['ASSET_002'], duration_sec: 5 },
        { id: 'SHOT_004', scene: 'INT. CITY - NIGHT', action: 'rain dimples the black water', visual_description: 'empty street', assets_used: ['ASSET_003'], duration_sec: 5 },
      ],
      scenes: [],
    }),
  }))

  await page.route('**/api/character/enrich', async (r) => {
    const body = r.request().postDataJSON() as { name?: string }
    order.push(`enrich:${body?.name ?? '?'}`)
    enrichNames.push(String(body?.name ?? ''))
    await r.fulfill({
      status: 200, contentType: 'application/json',
      body: JSON.stringify({
        personality: `${body?.name} is guarded and precise.`,
        backstory: `${body?.name} lost someone in the flood.`,
        wardrobe: 'wet wool, collar up',
        acting: 'holds stillness; speaks under the line',
      }),
    })
  })

  await page.route('**/api/shots/enhance', async (r) => {
    const body = r.request().postDataJSON() as {
      shots?: Array<{ id: string; characters?: string[] }>
      characters?: Array<{ name: string; acting?: string }>
    }
    order.push('enhance')
    enhanceCastSeen.push(body?.characters ?? [])
    const shots: Record<string, { action: string; visual: string; performance?: string }> = {}
    for (const s of body?.shots ?? []) {
      castPerShot[s.id] = s.characters
      const row: { action: string; visual: string; performance?: string } = {
        action: `directed ${s.id}`, visual: `lit ${s.id}`,
      }
      // MIRRORS claude_agents.enhance_shots exactly: "" only for a shot the caller
      // told us has nobody in it; a written paragraph otherwise. (The third case —
      // omitting the key entirely — is the "director said nothing" answer and is
      // covered by the BLOOM harness, not here.)
      row.performance = Array.isArray(s.characters) && s.characters.length === 0
        ? '' : `performance for ${s.id}`
      shots[s.id] = row
    }
    await r.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ shots }) })
  })

  // Landing at stage 3 starts its runner — stub the image endpoints so an assertion
  // about stage 2 can never cost a Seedream render.
  await page.route('**/api/assets/generate*', (r) => r.fulfill({ status: 500, contentType: 'application/json', body: '{"detail":"stubbed"}' }))

  await page.goto('/dashboard', { waitUntil: 'domcontentloaded' })
  await page.waitForTimeout(800)

  await openAutopilot(page)
  await page.getByTestId('autopilot-concept').fill('A neon-noir detective hunts a rogue AI in a flooded megacity')
  await page.getByTestId('autopilot-start').click()

  // Stage 2 approval is the signal the director pass finished: the fix runs both
  // passes BEFORE approveVersion, so "approved" means the dossiers and the shot
  // direction are already on the version.
  await expect.poll(async () => (await readStore(page)).stages['2']?.status,
    { timeout: 30_000, intervals: [400] }).toBe('approved')

  const st = await readStore(page)
  const s2 = st.stages['2']
  const data = s2.versions.find((v) => v.id === s2.activeVersionId)!.data
  const chars = (data.assets ?? []).filter((a) => a.type === 'character')
  const shots = data.shots ?? []

  console.log('[director-pass] enrich calls:', enrichNames.length, enrichNames)
  console.log('[director-pass] enhance calls:', enhanceCastSeen.length, 'cast seen:', JSON.stringify(enhanceCastSeen))
  console.log('[director-pass] call order:', order.join(' → '))
  console.log('[director-pass] cast per shot:', JSON.stringify(castPerShot))

  // 1) BOTH passes ran
  expect(enrichNames.sort()).toEqual(['Detective Kane', 'Mira'])
  expect(enhanceCastSeen.length).toBeGreaterThan(0)

  // 2) ORDER: every enrich finished before the first enhance started, and the shot
  //    pass was handed a cast whose acting profiles were already written.
  const lastEnrich = order.reduce((acc, o, i) => (o.startsWith('enrich') ? i : acc), -1)
  expect(order.indexOf('enhance')).toBeGreaterThan(lastEnrich)
  for (const cast of enhanceCastSeen) {
    expect(cast.map((c) => c.name).sort()).toEqual(['Detective Kane', 'Mira'])
    for (const c of cast) expect((c.acting ?? '').length).toBeGreaterThan(0)
  }

  // 3) The DATA landed on the approved version — the thing BLOOM was missing.
  expect(chars.length).toBe(2)
  for (const c of chars) {
    expect(c.personality?.length ?? 0, `${c.name}.personality`).toBeGreaterThan(0)
    expect(c.backstory?.length ?? 0, `${c.name}.backstory`).toBeGreaterThan(0)
    expect(c.wardrobe?.length ?? 0, `${c.name}.wardrobe`).toBeGreaterThan(0)
    expect(c.acting?.length ?? 0, `${c.name}.acting`).toBeGreaterThan(0)
  }
  expect(shots.length).toBe(4)

  // 4) WHO the caller said was in each shot — only the frontend knows an asset's type,
  //    so this resolution is what the backend's gate depends on.
  expect(castPerShot['SHOT_001']).toEqual(['Detective Kane'])
  expect(castPerShot['SHOT_002']).toEqual(['Detective Kane', 'Mira'])
  expect(castPerShot['SHOT_004'], 'a shot whose only asset is an environment resolves to nobody').toEqual([])

  // 5) Acting direction where there is an actor — and DELIBERATELY NONE where there
  //    is not. The blanket "every shot has a performance" assertion this replaces was
  //    asserting the exact bug the backend gate exists to prevent.
  for (const id of ['SHOT_001', 'SHOT_002', 'SHOT_003']) {
    const s = shots.find((x) => x.id === id)!
    expect(s.performance?.length ?? 0, `${id}.performance`).toBeGreaterThan(0)
  }
  const s4 = shots.find((x) => x.id === 'SHOT_004')!
  expect((s4.performance ?? '').trim(), 'SHOT_004 has no character in frame → no acting direction').toBe('')

  await page.getByTestId('autopilot-stop').click().catch(() => { /* run already finished */ })
})
