import { test, expect, noInheritedProject } from './isolation'

/**
 * P7 environment angles: the panel must read the PROJECT, not just this browser.
 *
 * The sheet (reverse angle + top-view map) has been saved to disk by the POST since
 * P5, but EnvironmentAnglesPanel used to seed its state from localStorage alone. A
 * sheet generated by another browser, another machine, a script or the autopilot was
 * therefore invisible: the panel offered "Generate" for work already paid for, and its
 * autoStart — which fires on !hasAngles the moment an environment is approved — went
 * on to REGENERATE and re-bill it. GET /api/assets/environment-angles is the read side
 * that closes that hole; these tests are what stop it reopening.
 *
 * Every backend call is intercepted, so the suite never touches a real server and no
 * generation can be billed by a test run. Set E2E_API_ORIGIN + E2E_ANGLES_LIVE=1 to
 * point the GET at a real backend instead of the fixture (that is how the payload
 * below was captured, from BLOOM's 39 environments on disk).
 */

const API_ORIGIN = process.env.E2E_API_ORIGIN ?? 'http://localhost:8000'
const LIVE = process.env.E2E_ANGLES_LIVE === '1'

const ROOT = `${process.env.HOME}/Documents/TakeOne-Project/BLOOM`
const ENV_NAME = 'Glass conference room'
/** A location that has never been generated — no Angles/ folder under it. Named
 *  rather than mocked so the empty-state tests hold in live mode too. */
const ENV_EMPTY = 'Unbuilt Location (no sheet on disk)'
const ENV_DIR = `${ROOT}/Assets/Environments/${ENV_NAME}`
const BASE_DISK = `${ENV_DIR}/Versions/v001.png`

const serve = (p: string) => `${API_ORIGIN}/api/asset/serve?path=${encodeURIComponent(p)}`

/** The exact shape GET /api/assets/environment-angles returns — one angle + a map. */
const SHEET = {
  angles: { reverse: serve(`${ENV_DIR}/Angles/Versions/v001.png`) },
  top_view: serve(`${ENV_DIR}/TopViewMap/Versions/v001.png`),
  qc: null,
}
const NO_SHEET = { angles: {}, top_view: '', qc: null }

const ver = (data: unknown) => ({ id: 'v1', createdAt: Date.now(), data, qcResult: null, approvalNotes: '' })
const stg = (status: string, data: unknown) => ({ status, activeVersionId: 'v1', versions: [ver(data)], isDirty: false })
const idle = () => ({ status: 'idle', activeVersionId: null, versions: [], isDirty: false })

const seed = (assetStatus: 'pending' | 'approved', envName: string = ENV_NAME) => ({
  state: {
    projectId: 'envangles', projectName: 'BLOOM', projectType: 'vfx_shot', projectStructure: {}, activeStage: 3,
    stages: {
      1: stg('approved', { concept: 'x', content: 'y' }),
      2: stg('approved', {
        assets: [{
          id: 'ASSET_ENV', name: envName, type: 'environment',
          visualDescription: 'a flooded glass-walled conference room', sceneRefs: [],
        }],
        shots: [], scenes: [],
      }),
      3: stg('approved', {
        assetStates: {
          ASSET_ENV: {
            imageUrls: [serve(BASE_DISK)], selectedUrl: serve(BASE_DISK),
            localPath: BASE_DISK, status: assetStatus, qcResult: null,
          },
        },
      }),
      4: idle(), 5: idle(), 6: idle(),
    },
    style: { id: 'photoreal', label: 'Photoreal', promptSuffix: '', negativePrompt: '', anchorImageRefs: [] },
    targetDurationSecs: 60, aspectRatio: '16:9', localFolderRoot: ROOT, approvedShotIds: [],
  },
  version: 3,
})

/**
 * Route every backend call. Returns a live counter of environment-angles POSTs —
 * the number that decides whether a test run would have COST money.
 */
async function stubBackend(page: import('@playwright/test').Page, sheet: object) {
  const posts = { count: 0 }
  await noInheritedProject(page)

  // ORDER MATTERS, and not the way it reads: Playwright tries route handlers in
  // REVERSE registration order, so the catch-all has to be registered FIRST or it
  // swallows the two specific routes below. Registered last-to-first it answered the
  // angles GET with "{}" and the panel showed its empty state — a green test that
  // was really testing nothing.
  await page.route('**/api/**', (r) => r.fulfill({
    status: 200, contentType: 'application/json', body: '{}',
  }))

  // Images are served straight through to whatever origin the payload names, so a
  // rendered <img> proves the URL the panel got is one a browser can actually load.
  await page.route('**/api/asset/serve*', (r) => r.continue())

  await page.route('**/api/assets/environment-angles*', async (route) => {
    if (route.request().method() === 'POST') {
      posts.count += 1
      return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(SHEET) })
    }
    if (LIVE) {
      const url = new URL(route.request().url())
      const res = await fetch(`${API_ORIGIN}/api/assets/environment-angles?${url.searchParams}`)
      return route.fulfill({ status: 200, contentType: 'application/json', body: await res.text() })
    }
    return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(sheet) })
  })
  return posts
}

/** The single asset card is already expanded on load; only the panel body is collapsed. */
const panelHeader = (page: import('@playwright/test').Page) =>
  page.getByRole('button', { name: /Environment Angles \+ Top View/ })

async function openStage3(page: import('@playwright/test').Page,
                          assetStatus: 'pending' | 'approved', envName: string = ENV_NAME) {
  await page.goto('/dashboard', { waitUntil: 'domcontentloaded' })
  await page.evaluate((s) => localStorage.setItem('takeone-pipeline-v1', JSON.stringify(s)),
                      seed(assetStatus, envName))
  await page.reload({ waitUntil: 'domcontentloaded' })
  await page.waitForTimeout(1500)
  await expect(page.getByTestId('asset-card-ASSET_ENV')).toBeVisible()
}

test('a sheet that exists on disk is SHOWN, and "Generate" is not offered', async ({ page }) => {
  const posts = await stubBackend(page, SHEET)
  await openStage3(page, 'approved')

  await expect(panelHeader(page)).toBeVisible()
  // The header badge counts what came back from the PROJECT — this browser has no
  // localStorage entry for it at all. Before the GET the panel read "no angles" and
  // offered to generate a sheet the project already had.
  await expect(page.locator('text=/^1 angle$/')).toBeVisible()

  await panelHeader(page).click()                        // expand the panel body
  await expect(page.getByRole('button', { name: /Generate Angles \+ Top View/ })).toHaveCount(0)
  await expect(page.getByRole('button', { name: /Regenerate Angles/ })).toBeVisible()

  // The angle and the map are real images the browser could load.
  const angle = page.locator('img[alt="reverse"]')
  await expect(angle).toBeVisible()
  expect(await angle.getAttribute('src')).toContain('/api/asset/serve')
  await expect.poll(() => angle.evaluate((el: HTMLImageElement) => el.naturalWidth),
    { timeout: 10_000, intervals: [300] }).toBeGreaterThan(0)
  await expect(page.locator('img[alt="Top View Map"]')).toBeVisible()

  expect(posts.count).toBe(0)                            // reading a sheet costs nothing
})

test('a location with NO sheet still gets the empty state and its Generate button', async ({ page }) => {
  await stubBackend(page, NO_SHEET)
  await openStage3(page, 'approved', ENV_EMPTY)

  await panelHeader(page).click()
  await expect(page.getByRole('button', { name: /Generate Angles \+ Top View/ })).toBeVisible()
  // The copy names what the generator actually makes (ENVIRONMENT_VIEWS has two
  // entries); it promised "4 camera angles (wide, reverse, high, eye-level)" for
  // long after the generator was cut to two.
  await expect(page.locator('text=/Generate the reverse angle \\+ an overhead top-view map/')).toBeVisible()
  await expect(page.locator('text=/wide, reverse, high, eye-level/')).toHaveCount(0)
})

test('approving an environment that ALREADY has a sheet does not re-bill it', async ({ page }) => {
  const posts = await stubBackend(page, SHEET)
  await openStage3(page, 'pending')

  // Approving is what arms autoStart (AssetGenerationView.setAutoAnglesFor).
  await page.getByRole('button', { name: /Approve Selected Variation/ }).click()
  await page.waitForTimeout(3000)                        // autoStart fires on a 0ms timer

  expect(posts.count).toBe(0)
  await expect(page.locator('text=/^1 angle$/')).toBeVisible()
})

test('CONTROL: the same approval DOES generate when the project has no sheet', async ({ page }) => {
  // Without this the test above proves nothing — it would pass on a panel that never
  // generates at all. Same seed, same click, empty project → exactly one POST.
  const posts = await stubBackend(page, NO_SHEET)
  await openStage3(page, 'pending', ENV_EMPTY)

  await page.getByRole('button', { name: /Approve Selected Variation/ }).click()
  await expect.poll(() => posts.count, { timeout: 15_000, intervals: [300] }).toBe(1)
})
